[gobot]
Host = "bot.betatechnologies.info"
ServerPort = ":3000" # default for go
FrontEnd = "nginx" # leave empty if you don't have a frontend, will use ServerPort instead
URLPathPrefix = "/go" # leave empty if you serve from the root URL above; no slash at end
PathToStaticFiles = "~/go/src/gobot" # where the lib/ and template/ dirs are; change as needed, no slash at end

# Database filename
# GoBotDSN = "/var/www/bot.betatechnologies.info/web/database/botmover.db?cache=shared&mode=rwc"
GoBotDSN = "btopensim:betaopenmv2008!@/gobot"

PDO_Prefix = "mysql"

EngineRunning = false
ShowPopulation = false

[log]
# Showing what logging options are available and the defaults for each
# FileName = "log/gobot.log"
# Format = "%{color}%{time:2006/01/02 15:04:05.0} %{shortfile} - %{shortfunc} ▶ %{level:.4s} %{id:03x}%{color:reset} %{message}"
# MaxSize = 500 # MBytes, integer
# MaxBackups = 3 # integer
# MaxAge = 28 # days, integer
#
# Severity logging: accepted values are CRITICAL, ERROR, WARNING, NOTICE, INFO, DEBUG
#
SeverityStderr	= DEBUG
SeverityFile	= DEBUG
SeveritySyslog	= CRITICAL

[opensim]
MapURL = "http://opensim.betatechnologies.info:8002/map-1-3646-3645-objects.jpg" # get a map tile
LSLSignaturePIN = "9876"